### ISSUE TITLE
Agenda for workshop 23 April 2020

### ISSUE THREAD

**Issue by frederikgeth** [frederikgeth/PowerModelsPrivacyPreserving.jl#8]
A list of things to discuss tomorrow in the meeting
- [x] Show how to use github `watch` functionality
- [x] Show how to install this package and how to put it in development mode https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/issues/2
- [x] Show how to run the unit tests, and add unit tests
- [x] Show how to branch the code, do pull request from branch to master, and code review https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/issues/7
- [x] Cleaning up the code https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/issues/3
- [x] We should run the code on more power flow cases https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/issues/6
- [x] Supporting more components to anonymise https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/issues/4
- [x] Larger scale tests: sanity checks and validation?
- [ ] Discuss new paper [1] -> next telco
- [ ] Discuss and compare with code https://github.com/wdvorkin/DP_CC_OPF, supplement to [1] -> next telco
- [x] Plan for milestones and writing a paper
- [ ] documentation?  -> next Fred todo
- [x] Review Andrew's approach

Suggested milestones
- [V 0.2](https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/milestone/1) 
- [V 0.3](https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/milestone/2)

Please add your agenda items to this thread :)

next meeting https://github.com/frederikgeth/PowerModelsPrivacyPreserving.jl/issues/17

[1] Dvorkin, V., Fioretto, F., Van Hentenryck, P., Kazempour, J., & Pinson, P. (2020). Differentially Private Optimal Power Flow for Distribution Grids, 1, 1–9. Retrieved from http://arxiv.org/abs/2004.03921
